owner: dandi
repo: upptime

sites:
  # alphabetic order on name
  - name: API (catch all)
    url: https://api.dandiarchive.org/
    assignees:
      - waxlamp
      - kabilar
  - name: API (Swagger)
    url: https://api.dandiarchive.org/swagger/
    assignees:
      - waxlamp
      - kabilar
  - name: API Staging (Swagger)
    url: https://api-staging.dandiarchive.org/swagger/
    assignees:
      - kabilar
  - name: Data portal
    url: https://dandiarchive.org/
    assignees:
      - waxlamp
      - kabilar
  - name: Data portal (000026 DLP)
    url: https://dandiarchive.org/dandiset/000026
    assignees:
      - kabilar
  - name: Data portal (000026 draft file browsing)
    url: https://dandiarchive.org/dandiset/000026/draft/files
    assignees:
      - kabilar
  - name: Data portal Staging
    url: https://gui-staging.dandiarchive.org/
    assignees:
      - kabilar
  - name: ETelemetry server
    url: https://etelemetry.dandiarchive.org/
    method: GET
    expectStatus: 200
    assignees:
      - satra
      - aaronkanzer
  - name: GitHub organization
    url: https://github.com/dandi
    assignees:
      - kabilar
  - name: Hub
    url: https://hub.dandiarchive.org
    assignees:
      - asmacdo
      - kabilar
  - name: Neurosift
    url: https://neurosift.app/
    assignees:
      - magland
      - kabilar
  - name: Ontobee
    url: https://ontobee.org/
    assignees:
      - yongqunh
  - name: PURL redirect example1 (ontobee)
    url: http://purl.obolibrary.org/obo/PATO_0000384
    maxRedirects: 6
    __dangerous__body_down_if_text_missing: '<Class rdf:about="http://purl.obolibrary.org/obo/PATO_0001894">'
    assignees:
      - yongqunh
  - name: identifiers.org redirect example1
    url: https://identifiers.org/DANDI:000027
    maxRedirects: 3
    # We cannot test for reaching specific dandiset due to Vue/JS frontend
    __dangerous__body_down_if_text_missing: 'DANDI Archive'
  - name: Registry of DataLad (dandisets query)
    url: https://registry.datalad.org/overview/?query=url%3A%22github.com%2Fdandisets%22
  - name: WebDAV
    url: https://webdav.dandiarchive.org
    assignees:
      - jwodder
      - kabilar
  - name: About
    url: https://about.dandiarchive.org/
    assignees:
      - kabilar
  - name: Docs
    url: https://docs.dandiarchive.org/
    assignees:
      - kabilar

status-website:
  cname: status.dandiarchive.org
  logoUrl: https://raw.githubusercontent.com/dandi/artwork/master/pics/dandi-logo-square.svg
  name: DANDI Status
  introTitle: "Status page for the DANDI project and related services."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/dandi/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO