# Change these first
owner: dandi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # alphabetic order on name
  - name: API (catch all)
    url: https://api.dandiarchive.org/
    assignees:
      - waxlamp
  - name: API (Swagger)
    url: https://api.dandiarchive.org/swagger/
    assignees:
      - waxlamp
  - name: API Staging (Swagger)
    url: https://api-staging.dandiarchive.org/swagger/
  - name: Data portal
    url: https://dandiarchive.org/
    assignees:
      - waxlamp
  - name: Data portal redirect
    url: https://www.dandiarchive.org/
    assignees:
      - kabilar    
  - name: Data portal (000026 DLP)
    url: https://dandiarchive.org/dandiset/000026
  - name: Data portal (000026 draft file browsing)
    url: https://dandiarchive.org/dandiset/000026/draft/files
  - name: Data portal Staging
    url: https://gui-staging.dandiarchive.org/
  - name: ETelemetry server
    url: https://rig.mit.edu/et/
    assignees:
      - satra
  - name: GitHub organization
    url: https://github.com/dandi
  - name: Hub
    url: https://hub.dandiarchive.org
    assignees:
      - asmacdo
  # To save money we take hub-staging down unless we are actively using it.
  # - name: Hub Staging
  #   url: https://hub-staging.dandiarchive.org
  - name: Neurosift
    url: https://neurosift.app/
    assignees:
      - magland
  - name: Ontobee
    url: https://ontobee.org/
    assignees:
      - yongqunh
  - name: PURL redirect example1 (ontobee)
    url: http://purl.obolibrary.org/obo/PATO_0000384
    maxRedirects: 6
    __dangerous__body_down_if_text_missing: '<Class rdf:about="http://purl.obolibrary.org/obo/PATO_0001894">'
    assignees:
      - yongqunh
  - name: identifiers.org redirect example1
    url: https://identifiers.org/DANDI:000027
    maxRedirects: 3
    # We cannot test for reaching specific dandiset due to Vue/JS frontend
    __dangerous__body_down_if_text_missing: 'DANDI Archive'
  - name: Registry of DataLad (dandisets query)
    url: https://registry.datalad.org/overview/?query=url%3A%22github.com%2Fdandisets%22
  - name: WebDAV
    url: https://webdav.dandiarchive.org
    assignees:
      - jwodder
  - name: About
    url: https://about.dandiarchive.org/
    assignees:
      - kabilar
  - name: Docs
    url: https://docs.dandiarchive.org/
    assignees:
      - kabilar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: dandiarchive.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/dandi/artwork/master/pics/dandi-logo-square.svg
  name: DANDI Upptime
  introTitle: "DANDI Project and related services upptime."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/dandi/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
