# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # alphabetic order on name
  - name: API (catch all)
    url: https://api.dandiarchive.org/
  - name: API (Swagger)
    url: https://api.dandiarchive.org/swagger/
  - name: API Staging (Swagger)
    url: https://api-staging.dandiarchive.org/swagger/
  - name: Data portal
    url: https://dandiarchive.org/
  - name: Data portal Staging
    url: https://gui-staging.dandiarchive.org/
  - name: ETelemetry server
    url: https://rig.mit.edu/et/
  - name: GitHub organization
    url: https://github.com/dandi
  - name: Hub
    url: https://hub.dandiarchive.org
  - name: Neurosift
    url: https://neurosift.app/
  - name: Ontobee
    url: https://ontobee.org/
  - name: PURL redirect example1 (ontobee)
    url: http://purl.obolibrary.org/obo/PATO_0000384
  - name: Registry of DataLad (dandisets query)
    url: https://registry.datalad.org/overview/?query=url%3A%22github.com%2Fdandisets%22
  - name: WebDAV
    url: https://webdav.dandiarchive.org
  - name: Website
    url: https://www.dandiarchive.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: www.dandiarchive.org
  baseUrl: uptime
  logoUrl: https://raw.githubusercontent.com/dandi/artwork/master/pics/dandi-logo-square.svg
  name: DANDI Upptime
  introTitle: "DANDI Project and related services uptime."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/dandi/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
